# Generated by Django 5.0 on 2024-05-28 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdv',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Il numero di telefono deve contenere 10 cifre.', regex='^\\d{10}$')]),
        ),
    ]
